import React from "react";
import Head from "next/head";

import { VideoBanner } from "../components/VideoBanner/VideoBanner";
import { GetStaticProps, NextPage } from "next";
import { PromoCard } from "@components/PromoCard/PromoCard";
import { getProducts, Product } from "@square-api/index";
import { getCategoryId } from "@square-api/categories";
import { getCustomAttributeId } from "@square-api/util";

interface HomeProps {
  featuredProducts: Product[];
}

const Home: NextPage = ({ featuredProducts }: HomeProps) => {
  console.log(featuredProducts);
  return (
    <>
      <Head>
        <title>Suffer Under Sorrow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/iee0mvp.css" />
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.0/css/solid.css"
        ></link>
      </Head>

      <VideoBanner src="/video/lightbringer.mp4">
        <PromoCard date="11 . 11 . 22" heading="Lightbringer" href="/" />
      </VideoBanner>

      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const products = JSON.stringify(
    await getProducts({
      customAttributeFilters: [
        {
          customAttributeDefinitionId: await getCustomAttributeId(
            "is_featured"
          ),
          boolFilter: true,
        },
      ],
    })
  );

  return {
    props: { featuredProducts: JSON.parse(products) },
  };
};

export default Home;
