import React from "react";
import type { GetServerSideProps } from "next";
import Layout from "../components/Layout";
import Post, { PostProps } from "../components/Post";
import Head from "next/head";

import prisma from "../lib/prisma";
import { VideoBanner } from "../components/VideoBanner/VideoBanner";

export const getServerSideProps: GetServerSideProps = async () => {
  // const feed = await prisma.post.findMany({
  //   where: {
  //     published: true,
  //   },
  //   include: {
  //     author: {
  //       select: {
  //         name: true,
  //       },
  //     },
  //   },
  // });
  return {
    props: { feed: [] },
  };
};

type Props = {
  feed: PostProps[];
};

const Home: React.FC<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Suffer Under Sorrow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VideoBanner />
    </>
  );
};

export default Home;
